MaithCommonUsersBundle_admin_users:
    resource: "@MaithCommonUsersBundle/Resources/config/routing/user.yml"
    prefix:   /admin/users


MaithCommonUsersBundle_admin_group_roles:
    resource: "@MaithCommonUsersBundle/Resources/config/routing/grouprole.yml"
    prefix:   /admin/permissions

