grouprole:
    path:     /
    defaults: { _controller: "MaithCommonUsersBundle:GroupRole:index" }

grouprole_show:
    path:     /{id}/show
    defaults: { _controller: "MaithCommonUsersBundle:GroupRole:show" }

grouprole_new:
    path:     /new
    defaults: { _controller: "MaithCommonUsersBundle:GroupRole:new" }

grouprole_create:
    path:     /create
    defaults: { _controller: "MaithCommonUsersBundle:GroupRole:create" }
    methods:  [POST]

grouprole_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaithCommonUsersBundle:GroupRole:edit" }

grouprole_update:
    path:     /{id}/update
    defaults: { _controller: "MaithCommonUsersBundle:GroupRole:update" }
    methods:  [POST, PUT]

grouprole_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaithCommonUsersBundle:GroupRole:delete" }
    methods:  [POST, DELETE]
