user:
    path:     /
    defaults: { _controller: "MaithCommonUsersBundle:User:index" }

user_show:
    path:     /profile
    defaults: { _controller: "MaithCommonUsersBundle:User:show" }

user_edit_profile:
    path:     /profile/editar.html
    defaults: { _controller: "MaithCommonUsersBundle:User:editProfile" }

user_edit_profile_password:
    path:     /profile/change-password
    defaults: { _controller: "MaithCommonUsersBundle:User:editPassword" }

user_edit_profile_email_password:
    path:     /profile/change-email-password
    defaults: { _controller: "MaithCommonUsersBundle:User:editEmailPassword" }
    
user_new:
    path:     /new
    defaults: { _controller: "MaithCommonUsersBundle:User:new" }

user_create:
    path:     /create
    defaults: { _controller: "MaithCommonUsersBundle:User:create" }
    requirements: { _method: post }

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaithCommonUsersBundle:User:edit" }

user_update:
    path:     /{id}/update
    defaults: { _controller: "MaithCommonUsersBundle:User:update" }
    requirements: { _method: post|put }

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaithCommonUsersBundle:User:delete" }
    requirements: { _method: post|delete }

user_block_unblock:
    path:     /{id}/{status}/block-unblock
    defaults: { _controller: "MaithCommonUsersBundle:User:blockUnblock" }
